settings:
  world: 'world'
  minPlayers: 2
  raidLocation: '290 97 190'
  defLocation: '230 107 189'
  toggleLocation: '201 108 205'
  enderman_locations:
    location1: '360 119 84'
    location2: '360 119 86'
    location3: '360 119 88'
sqlSettings:
  user: 'root'
  password: ''
  host: 'localhost'
  port: 3306
  database: 'data'

