settings:
  world: 'world'
  minPlayers: 2
  raidLocation: '290 97 190'
  defLocation: '230 107 189'
  toggleLocation: '201 108 205'
  endermanLocation: '190 107 183'
sqlSettings:
  user: 'root'
  password: ''
  host: 'localhost'
  port: 3306
  database: 'data'

